language: python
python: 3.6

services:
    - docker

branches:
  only:
    - master

jobs:
    include:
        - name: "Trellis - Triplestore"
          before_install: docker-compose -f trellis-compose.yml up -d
          script:
              - python verify_running.py --baseurl http://localhost/
              - python setup.py test -a "--baseurl=http://localhost/"

        - name: "Trellis - H2"
          before_install: docker-compose -f trellis-h2-compose.yml up -d
          script:
              - python verify_running.py --baseurl http://localhost/
              - python setup.py test -a "--baseurl=http://localhost/"

        - name: "Trellis - PostgreSQL"
          before_install: docker-compose -f trellis-postgres-compose.yml up -d
          script:
              - python verify_running.py --baseurl http://localhost/
              - python setup.py test -a "--baseurl=http://localhost/"
              - docker ps -a
              - sh run_ldp_testsuite.sh
              - aws s3 cp --recursive --exclude "*" --include "*.html" --include "*.ttl" ./report s3://$AWS_BUCKET/ldp/report
              - aws s3 cp --recursive --content-type "application/ld+json" --exclude "*" --include "*.jsonld" ./report s3://$AWS_BUCKET/ldp/report

