language: python
python: 3.6

services:
    - docker

before_install:
    - docker-compose --version
    - docker-compose up -d
    - docker ps -a

script:
    - sleep 60
    - python setup.py test -a "--baseurl=http://localhost:8080/"
    - python setup.py test -a "--baseurl=http://localhost/"
