language: python
python: 3.6

services:
    - docker

jobs:
    include:
        - name: "Trellis"
          before_install:
              - docker-compose --version
              - docker-compose -f trellis-compose.yml up -d

        - name: "Trellis-ext-db"
          before_install:
              - docker-compose --version
              - docker-compose -f trellis-ext-db-compose.yml up -d

script:
  - docker ps -a
  - python verify_running.py --baseurl http://localhost/
  - python setup.py test -a "--baseurl=http://localhost/"

