version: "3"
services:
  trellis-db:
    image: trellisldp/trellis-postgresql:develop
    environment:
      MP_JWT_VERIFY_PUBLICKEY_LOCATION: "https://www.trellisldp.org/tests/jwks.json"
      QUARKUS_DATASOURCE_USERNAME: trellis
      QUARKUS_DATASOURCE_PASSWORD: trellis
      QUARKUS_DATASOURCE_JDBC_URL: jdbc:postgresql://db/trellis
      TRELLIS_HTTP_WEAK_ETAG: "false"
      TRELLIS_HTTP_MEMENTO_HEADER_DATES: "false"
      TRELLIS_HTTP_PRECONDITION_REQUIRED: "true"
      TRELLIS_JDBC_LDP_TYPE: "true"
    ports:
      - 80:8080
    depends_on:
      - db
  db:
    image: postgres
    environment:
      POSTGRES_DB: trellis
      POSTGRES_PASSWORD: trellis
      POSTGRES_USER: trellis

