version: "3"
services:
  trellis:
    image: trellisldp/trellis-triplestore:develop
    environment:
      MP_JWT_VERIFY_PUBLICKEY_LOCATION: "https://www.trellisldp.org/tests/jwks.json"
      TRELLIS_HTTP_WEAK_ETAG: "false"
      TRELLIS_HTTP_MEMENTO_HEADER_DATES: "false"
      TRELLIS_HTTP_PRECONDITION_REQUIRED: "true"
      TRELLIS_TRIPLESTORE_LDP_TYPE: "true"
      TRELLIS_TRIPLESTORE_RDF_LOCATION: /opt/trellis/data/rdf
      TRELLIS_FILE_BINARY_PATH: /opt/trellis/data/binary
      TRELLIS_FILE_MEMENTO_PATH: /opt/trellis/data/memento
    ports:
      - 80:8080

